int insert_index = 0, reached_loop_end = 0;
_Bool searching_for_start = 1;
_Bool previous_char_bracket = 0;
_Bool rendering_partial = 0;
_Bool getting_loop_tag = 0;
_Bool previous_double_bracket = 0;
char ch;
char word_ch;
FILE *file;
void interpolate_string(int k, char keys_array[][k], int v, char b[][v], char *w);
void validate_character(int k, char keys_array[][k], int v, char b[][v], char *word, int loop_index);
void validate_character_for_start(void);
void validate_character_for_end(int k, char keys_array[][k], int v, char b[][v], char *word, int loop_index);
void validate_char_for_prev_bracket(void);
void validate_char_for_prev_bracket_end(int k, char a[][k], int v, char b[][v], char *w, int loop_index);
void insert_char(char c, char *word);
void interpolate_word(int k, char a[][k], int v, char b[][v], char *word, int loop_count);
void end_interpolation_word(char *word);
void render_partial(int k, char a[][k], int v, char b[][v], char *w);
void render_loop(int k, char a[][k], int v, char b[][v], char *w, int i, int c, int s);
void exit_with_usage(void);
