int max_keys = 100;
_Bool escape_html = 0;
_Bool searching_for_key = 1;
_Bool searching_for_value = 0;
_Bool searching_for_colon = 0;
_Bool adding_key = 0;
_Bool adding_value = 0;
_Bool is_value_a_string = 0;
_Bool previous_ch_escape = 0;
char character;
int word_index = 0;
int value_index = 0;

void json_to_array(char json[], int k, char a[][k], int v, char values_array[][v], char *w);
char* find_json_value(char key[], int k, char a[][k], int v, char b[][v]);
void add_char_to_word(char c, char *w);
static void add_char_to_value(char c, char *w);
static void add_string_to_word(char[], char *w);
void end_adding_key(int k, char a[][k], char *w);
void end_adding_value(int v, char b[][v], char *w);
void search_for_key(void);
void add_key_char(int k, char a[][k], char *w);
void search_for_colon(void);
void search_for_value(char *w);
void add_value_char(int v, char b[][v], char *w);
void analyse_character(int k, char a[][k], int v, char b[][v], char *w);
_Bool reached_end_of_word(void);
